#!/usr/bin/env sh
# Rebuilds assets/wasm from crates/. Needs: rustup target wasm32-unknown-unknown,
# and wasm-bindgen-cli of the same version as the wasm-bindgen crate in Cargo.lock.
set -eu
cd "$(dirname "$0")/.."

cargo build -p idea-wasm --release --target wasm32-unknown-unknown
wasm-bindgen --target no-modules --no-typescript --out-dir target/wasm-out \
  target/wasm32-unknown-unknown/release/idea_wasm.wasm

mkdir -p assets/wasm
cp target/wasm-out/idea_wasm.js assets/wasm/idea_wasm.js
# The binary goes into a script as base64: browsers refuse fetch() of a .wasm
# file from file://, and the site must open by double-clicking index.html.
{
  printf '// Generated by scripts/build-wasm.sh from crates/idea-wasm. Do not edit.\n'
  printf 'window.IDEA_WASM_BASE64 = "'
  base64 < target/wasm-out/idea_wasm_bg.wasm | tr -d '\n'
  printf '";\n'
} > assets/wasm/idea_wasm_bytes.js

echo "wasm: $(wc -c < target/wasm-out/idea_wasm_bg.wasm) bytes"
